### ISSUE TITLE
[FEATURE] Git Status 에 따른 value 표시 기능 구현

### ISSUE THREAD

**Issue by dn7638** [CAU-OSS-project-practice/OSS-file-manager#12]
### value에 따른 값은 각 상태 자리의 비트 on, off로 판단
1: GIT_STATUS_CURRENT
2: GIT_STATUS_INDEX_NEW
4: GIT_STATUS_INDEX_MODIFIED
8: GIT_STATUS_INDEX_DELETED
16: GIT_STATUS_INDEX_RENAMED
32: GIT_STATUS_INDEX_TYPECHANGE
64: GIT_STATUS_WT_NEW
128: GIT_STATUS_WT_MODIFIED
256: GIT_STATUS_WT_DELETED
512: GIT_STATUS_WT_TYPECHANGE
1024: GIT_STATUS_WT_RENAMED
2048: GIT_STATUS_WT_UNREADABLE
4096: GIT_STATUS_IGNORED
8192: GIT_STATUS_CONFLICTED

## 📝  To-do

- [] todo! 현재 디렉토리가 깃이 관리하는 레포지토리인지 체크
- [] todo! 현재 디렉토리에 있는 파일들의 상태 체크
- [] 파일, 폴더등 타입에 따라 다른 로직 구현
