### ISSUE TITLE
[FEATURE] 선택된 파일의 git status에 관한 정보 제공

### ISSUE THREAD

**Issue by realisshomyang** [CAU-OSS-project-practice/OSS-file-manager#3]
## 📌  Issue

GUI 상에서 선택된 파일, 그 파일이 포함된 디렉토리의 git status 
### 

## 📝  To-do

- [x] GUI 상에서 선택된 파일에 대한 정보를 담는 전역변수 만들기
- [x] 선택된 파일의 Git status 리턴
- [x] 선택된 파일 상위 디렉토리가 Git repository인지 확인해주는 함수 구현
