### ISSUE TITLE
[FIX]  .git폴더가 있는 디렉토리의 하위 디렉토리의 버튼 액션 오류 해결 및 select함수 구조 개선

### ISSUE THREAD

**Issue by realisshomyang** [CAU-OSS-project-practice/OSS-file-manager#31]
## 📌  Issue
.git폴더가 있는 하위 디렉토리의 버튼 액션 오류 해결 및 select함수 구조 개선
### 

## 📝  To-do

- [x] select 함수 구조 개선
- [x] .git폴더가 있는 하위 디렉토리의 버튼 액션 오류 
- [x] 커밋,mv(untracked제외) 항상 활성화
