### ISSUE TITLE
[FEATURE] 브랜치 UI 구현하여 사용자 입력 받기

### ISSUE THREAD

**Issue by rbgksqkr** [CAU-OSS-project-practice/OSS-file-manager#51]
## 📝  To-do

- [x] create UI 구현
- [x] delete UI 구현
- [x] rename UI 구현
- [x] checkout UI 구현
- [x] 로컬 브랜치 리스트 보여주기

## 📆 Date

23.05.23 ~ 23.05.24
