### ISSUE TITLE
[FEATURE] View 부분 구현

### ISSUE THREAD

**Issue by dn7638** [CAU-OSS-project-practice/OSS-file-manager#6]
## 📝  To-do

- [ ] view 에서 새로운 칼럼 추가해주기
- [ ] view의 새 칼럼을 위해 관련 객체들에 속성 추가
- [ ] temp 이미지 생성
